# Uses ISO units. For example, use 'm' for length.
general:
  dribble_distance_thres: 0.4           # theshold distance between nubot and football below which dribble ball
  dribble_angle_thres: 20.0             # kicking mechanism aligning with football; allowed maximum angle error in degrees
  noise_scale: 0.00                     # the scale of gaussian noise (m)
  noise_rate: 0.01                       # how frequent the noise is generated

cyan:
  prefix: "NuBot"             # Nubot name prefix. 
  num: 5 
 
magenta:
  prefix: "rival"            # Rival name prefix. 
  num: 5

field:
  length: 22                     # Use integer!   used in spawn_model_script
  width: 14                      # Use integer!  used in spawn_model_script
  
football:
  name: "football"                   # football model name
  chassis_link: "football::chassis"     # football body link name  

